nb_classes: 17
gene: 'gene'

having_test_set: True
traintest: True

test: False
eval: False
combine_eyes: False
label_column: 'gene_label'
finetune: 'finetune'

weight_cfp: "/data/hdd/zhengyi/retfound_weight/RETFound_mae_natureCFP.pth"
weight_oct: "/data/hdd/zhengyi/retfound_weight/RETFound_mae_natureOCT.pth"
data_path: "/data/hdd/zhengyi/zhengyi/IRD_Model_Training/downstream_data/IRD/task2_gene_20250320_17label/image_trainValTest/"
csv_path: "/data/hdd/zhengyi/zhengyi/IRD_Model_Training/downstream_data/IRD/test/train_val_test/"
resume: ''

output_dir: "/data/hdd/zhengyi/zhengyi/IRD_Model_Training/downstream_data/IRD/test/train_val_test/test/"

seed_count: 5
epochs: 50
batch_size: 32
blr: 0.005
layer_decay: 0.65
drop_path: 0.2
min_lr: 1e-6
warmup_epochs: 10
input_size: 224
weight_decay: 0.05

use_mean_pooling: True
init_scale: 0.001



log_wandb: False
log_tensorboard: False
wandb_project: 'eyenet-finetune-cls'
wandb_entity: null
wandb_run_name: IDRiD-test

save_confusion_matrix: True


model: multivit_large
patch_size: 16
num_global_tokens: 1
